apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aria-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: aria.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aria-frontend-svc
            port:
              number: 80
  - host: api.aria.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aria-backend-svc
            port:
              number: 8000
